apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sample-app
  namespace: sample-app
  labels:
    app: sample-app
spec:
  podSelector:
    matchLabels:
      app: sample-app
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 80
          protocol: TCP
  egress:
    - {}
